// <auto-generated />
using System;
using DbServer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbServer.Migrations
{
    [DbContext(typeof(AlloyContext))]
    [Migration("20260116223804_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Common.Database.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("AccStatsId")
                        .HasColumnType("int")
                        .HasColumnName("acc_stats_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("GuildMemberId")
                        .HasColumnType("int")
                        .HasColumnName("guild_member_id");

                    b.Property<string>("GuildName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("guild_name");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_admin");

                    b.Property<bool?>("IsBanned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_banned");

                    b.Property<int?>("LoginId")
                        .HasColumnType("int")
                        .HasColumnName("login_id");

                    b.Property<short?>("MaxChars")
                        .HasColumnType("smallint")
                        .HasColumnName("max_chars");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.Property<short?>("NextCharId")
                        .HasColumnType("smallint")
                        .HasColumnName("next_char_id");

                    b.Property<short?>("Rank")
                        .HasColumnType("smallint")
                        .HasColumnName("rank");

                    b.Property<short?>("VaultCount")
                        .HasColumnType("smallint")
                        .HasColumnName("vault_count");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AccStatsId" }, "acc_stats_id");

                    b.HasIndex(new[] { "GuildMemberId" }, "guild_member_id");

                    b.HasIndex(new[] { "LoginId" }, "login_id");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Common.Database.Models.AccountSkin", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<int>("SkinType")
                        .HasColumnType("int")
                        .HasColumnName("skin_type");

                    b.HasKey("AccountId", "SkinType")
                        .HasName("PRIMARY");

                    b.ToTable("Account_Skins", (string)null);
                });

            modelBuilder.Entity("Common.Database.Models.AccountStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<uint?>("BestCharFame")
                        .HasColumnType("int unsigned")
                        .HasColumnName("best_char_fame");

                    b.Property<uint?>("CurrentCredits")
                        .HasColumnType("int unsigned")
                        .HasColumnName("current_credits");

                    b.Property<uint?>("CurrentFame")
                        .HasColumnType("int unsigned")
                        .HasColumnName("current_fame");

                    b.Property<uint?>("TotalCredits")
                        .HasColumnType("int unsigned")
                        .HasColumnName("total_credits");

                    b.Property<uint?>("TotalFame")
                        .HasColumnType("int unsigned")
                        .HasColumnName("total_fame");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Account_Stats", (string)null);
                });

            modelBuilder.Entity("Common.Database.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("AccCharId")
                        .HasColumnType("int")
                        .HasColumnName("acc_char_id");

                    b.Property<int?>("AccId")
                        .HasColumnType("int")
                        .HasColumnName("acc_id");

                    b.Property<int?>("CharStatsId")
                        .HasColumnType("int")
                        .HasColumnName("char_stats_id");

                    b.Property<int?>("CombatStatsId")
                        .HasColumnType("int")
                        .HasColumnName("combat_stats_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<uint?>("CurrentFame")
                        .HasColumnType("int unsigned")
                        .HasColumnName("current_fame");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DungeonStatsId")
                        .HasColumnType("int")
                        .HasColumnName("dungeon_stats_id");

                    b.Property<int?>("ExploStatsId")
                        .HasColumnType("int")
                        .HasColumnName("explo_stats_id");

                    b.Property<bool?>("HasBackpack")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_backpack");

                    b.Property<ushort?>("HealthPotions")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("health_potions");

                    b.Property<bool?>("IsDead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_dead");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("KillStatsId")
                        .HasColumnType("int")
                        .HasColumnName("kill_stats_id");

                    b.Property<ushort?>("Level")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("level");

                    b.Property<ushort?>("MagicPotions")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("magic_potions");

                    b.Property<ushort?>("ObjectType")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("object_type");

                    b.Property<ushort?>("PetType")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("pet_type");

                    b.Property<ushort?>("SkinType")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("skin_type");

                    b.Property<ushort?>("TextureOne")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("texture_one");

                    b.Property<ushort?>("TextureTwo")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("texture_two");

                    b.Property<uint?>("XpPoints")
                        .HasColumnType("int unsigned")
                        .HasColumnName("xp_points");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AccId" }, "acc_id");

                    b.HasIndex(new[] { "CharStatsId" }, "char_stats_id");

                    b.HasIndex(new[] { "CombatStatsId" }, "combat_stats_id");

                    b.HasIndex(new[] { "DungeonStatsId" }, "dungeon_stats_id");

                    b.HasIndex(new[] { "ExploStatsId" }, "explo_stats_id");

                    b.HasIndex(new[] { "KillStatsId" }, "kill_stats_id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Common.Database.Models.CharacterDeath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("CharId")
                        .HasColumnType("int")
                        .HasColumnName("char_id");

                    b.Property<DateTime?>("DeadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dead_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<uint?>("DeathFame")
                        .HasColumnType("int unsigned")
                        .HasColumnName("death_fame");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CharId" }, "char_id");

                    b.ToTable("Character_Death", (string)null);
                });

            modelBuilder.Entity("Common.Database.Models.CharacterInventory", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    b.Property<int>("SlotId")
                        .HasColumnType("int")
                        .HasColumnName("slot_id");

                    b.Property<byte[]>("ItemData")
                        .HasColumnType("blob")
                        .HasColumnName("item_data");

                    b.Property<ushort?>("ItemType")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("item_type");

                    b.HasKey("CharacterId", "SlotId")
                        .HasName("PRIMARY");

                    b.ToTable("Character_Inventory", (string)null);
                });

            modelBuilder.Entity("Common.Database.Models.CharacterStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<uint?>("Attack")
                        .HasColumnType("int unsigned")
                        .HasColumnName("attack");

                    b.Property<uint?>("Defense")
                        .HasColumnType("int unsigned")
                        .HasColumnName("defense");

                    b.Property<uint?>("Dexterity")
                        .HasColumnType("int unsigned")
                        .HasColumnName("dexterity");

                    b.Property<uint?>("Hp")
                        .HasColumnType("int unsigned")
                        .HasColumnName("hp");

                    b.Property<uint?>("MaxHp")
                        .HasColumnType("int unsigned")
                        .HasColumnName("max_hp");

                    b.Property<uint?>("MaxMp")
                        .HasColumnType("int unsigned")
                        .HasColumnName("max_mp");

                    b.Property<uint?>("Mp")
                        .HasColumnType("int unsigned")
                        .HasColumnName("mp");

                    b.Property<uint?>("Speed")
                        .HasColumnType("int unsigned")
                        .HasColumnName("speed");

                    b.Property<uint?>("Vitality")
                        .HasColumnType("int unsigned")
                        .HasColumnName("vitality");

                    b.Property<uint?>("Wisdom")
                        .HasColumnType("int unsigned")
                        .HasColumnName("wisdom");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Character_Stats", (string)null);
                });

            modelBuilder.Entity("Common.Database.Models.ClassStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("AccStatsId")
                        .HasColumnType("int")
                        .HasColumnName("acc_stats_id");

                    b.Property<uint?>("BestFame")
                        .HasColumnType("int unsigned")
                        .HasColumnName("best_fame");

                    b.Property<ushort?>("BestLevel")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("best_level");

                    b.Property<ushort?>("ObjectType")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("object_type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AccStatsId" }, "acc_stats_id")
                        .HasDatabaseName("acc_stats_id1");

                    b.ToTable("Class_Stats", (string)null);
                });

            modelBuilder.Entity("Common.Database.Models.CombatStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<ushort?>("AbilitiesUsed")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("abilities_used");

                    b.Property<uint?>("DamageDealt")
                        .HasColumnType("int unsigned")
                        .HasColumnName("damage_dealt");

                    b.Property<uint?>("DamageTaken")
                        .HasColumnType("int unsigned")
                        .HasColumnName("damage_taken");

                    b.Property<uint?>("LevelUpAssists")
                        .HasColumnType("int unsigned")
                        .HasColumnName("level_up_assists");

                    b.Property<ushort?>("PotionsDrank")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("potions_drank");

                    b.Property<ulong?>("Shots")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("shots");

                    b.Property<uint?>("ShotsHit")
                        .HasColumnType("int unsigned")
                        .HasColumnName("shots_hit");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Combat_Stats", (string)null);
                });

            modelBuilder.Entity("Common.Database.Models.DungeonStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<ushort?>("CompletedCount")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("completed_count");

                    b.Property<string>("DungeonName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dungeon_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Dungeon_Stats", (string)null);
                });

            modelBuilder.Entity("Common.Database.Models.ExplorationStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<uint?>("Escapes")
                        .HasColumnType("int unsigned")
                        .HasColumnName("escapes");

                    b.Property<uint?>("MinutesActive")
                        .HasColumnType("int unsigned")
                        .HasColumnName("minutes_active");

                    b.Property<uint?>("NearDeathEscapes")
                        .HasColumnType("int unsigned")
                        .HasColumnName("near_death_escapes");

                    b.Property<uint?>("QuestsCompleted")
                        .HasColumnType("int unsigned")
                        .HasColumnName("quests_completed");

                    b.Property<uint?>("Teleports")
                        .HasColumnType("int unsigned")
                        .HasColumnName("teleports");

                    b.Property<uint?>("TilesUncovered")
                        .HasColumnType("int unsigned")
                        .HasColumnName("tiles_uncovered");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Exploration_Stats", (string)null);
                });

            modelBuilder.Entity("Common.Database.Models.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<uint?>("CurrentFame")
                        .HasColumnType("int unsigned")
                        .HasColumnName("current_fame");

                    b.Property<string>("GuildBoard")
                        .HasColumnType("text")
                        .HasColumnName("guild_board");

                    b.Property<short?>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<uint?>("TotalFame")
                        .HasColumnType("int unsigned")
                        .HasColumnName("total_fame");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Common.Database.Models.GuildMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("GuildId")
                        .HasColumnType("int")
                        .HasColumnName("guild_id");

                    b.Property<short?>("GuildRank")
                        .HasColumnType("smallint")
                        .HasColumnName("guild_rank");

                    b.Property<DateTime?>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "GuildId" }, "guild_id");

                    b.ToTable("Guild_Members", (string)null);
                });

            modelBuilder.Entity("Common.Database.Models.KillStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<ushort?>("BlueBags")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("blue_bags");

                    b.Property<ushort?>("CubeAssists")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("cube_assists");

                    b.Property<ushort?>("CubeKills")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("cube_kills");

                    b.Property<ushort?>("CyanBags")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("cyan_bags");

                    b.Property<uint?>("GodAssists")
                        .HasColumnType("int unsigned")
                        .HasColumnName("god_assists");

                    b.Property<uint?>("GodKills")
                        .HasColumnType("int unsigned")
                        .HasColumnName("god_kills");

                    b.Property<uint?>("MonsterAssists")
                        .HasColumnType("int unsigned")
                        .HasColumnName("monster_assists");

                    b.Property<uint?>("MonsterKills")
                        .HasColumnType("int unsigned")
                        .HasColumnName("monster_kills");

                    b.Property<ushort?>("OryxAssists")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("oryx_assists");

                    b.Property<ushort?>("OryxKills")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("oryx_kills");

                    b.Property<ushort?>("WhiteBags")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("white_bags");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Kill_Stats", (string)null);
                });

            modelBuilder.Entity("Common.Database.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text")
                        .HasColumnName("password_salt");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique()
                        .HasDatabaseName("name1");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Common.Database.Models.Account", b =>
                {
                    b.HasOne("Common.Database.Models.AccountStat", "AccStats")
                        .WithMany("Accounts")
                        .HasForeignKey("AccStatsId")
                        .HasConstraintName("Accounts_ibfk_1");

                    b.HasOne("Common.Database.Models.GuildMember", "GuildMember")
                        .WithMany("Accounts")
                        .HasForeignKey("GuildMemberId")
                        .HasConstraintName("Accounts_ibfk_3");

                    b.HasOne("Common.Database.Models.Login", "Login")
                        .WithMany("Accounts")
                        .HasForeignKey("LoginId")
                        .HasConstraintName("Accounts_ibfk_2");

                    b.Navigation("AccStats");

                    b.Navigation("GuildMember");

                    b.Navigation("Login");
                });

            modelBuilder.Entity("Common.Database.Models.AccountSkin", b =>
                {
                    b.HasOne("Common.Database.Models.Account", "Account")
                        .WithMany("AccountSkins")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("Account_Skins_ibfk_1");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Common.Database.Models.Character", b =>
                {
                    b.HasOne("Common.Database.Models.Account", "Acc")
                        .WithMany("Characters")
                        .HasForeignKey("AccId")
                        .HasConstraintName("Characters_ibfk_1");

                    b.HasOne("Common.Database.Models.CharacterStat", "CharStats")
                        .WithMany("Characters")
                        .HasForeignKey("CharStatsId")
                        .HasConstraintName("Characters_ibfk_2");

                    b.HasOne("Common.Database.Models.CombatStat", "CombatStats")
                        .WithMany("Characters")
                        .HasForeignKey("CombatStatsId")
                        .HasConstraintName("Characters_ibfk_4");

                    b.HasOne("Common.Database.Models.DungeonStat", "DungeonStats")
                        .WithMany("Characters")
                        .HasForeignKey("DungeonStatsId")
                        .HasConstraintName("Characters_ibfk_6");

                    b.HasOne("Common.Database.Models.ExplorationStat", "ExploStats")
                        .WithMany("Characters")
                        .HasForeignKey("ExploStatsId")
                        .HasConstraintName("Characters_ibfk_3");

                    b.HasOne("Common.Database.Models.KillStat", "KillStats")
                        .WithMany("Characters")
                        .HasForeignKey("KillStatsId")
                        .HasConstraintName("Characters_ibfk_5");

                    b.Navigation("Acc");

                    b.Navigation("CharStats");

                    b.Navigation("CombatStats");

                    b.Navigation("DungeonStats");

                    b.Navigation("ExploStats");

                    b.Navigation("KillStats");
                });

            modelBuilder.Entity("Common.Database.Models.CharacterDeath", b =>
                {
                    b.HasOne("Common.Database.Models.Character", "Char")
                        .WithMany("CharacterDeaths")
                        .HasForeignKey("CharId")
                        .HasConstraintName("Character_Death_ibfk_1");

                    b.Navigation("Char");
                });

            modelBuilder.Entity("Common.Database.Models.CharacterInventory", b =>
                {
                    b.HasOne("Common.Database.Models.Character", "Character")
                        .WithMany("CharacterInventories")
                        .HasForeignKey("CharacterId")
                        .IsRequired()
                        .HasConstraintName("Character_Inventory_ibfk_1");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Common.Database.Models.ClassStat", b =>
                {
                    b.HasOne("Common.Database.Models.AccountStat", "AccStats")
                        .WithMany("ClassStats")
                        .HasForeignKey("AccStatsId")
                        .HasConstraintName("Class_Stats_ibfk_1");

                    b.Navigation("AccStats");
                });

            modelBuilder.Entity("Common.Database.Models.GuildMember", b =>
                {
                    b.HasOne("Common.Database.Models.Guild", "Guild")
                        .WithMany("GuildMembers")
                        .HasForeignKey("GuildId")
                        .HasConstraintName("Guild_Members_ibfk_1");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Common.Database.Models.Account", b =>
                {
                    b.Navigation("AccountSkins");

                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Common.Database.Models.AccountStat", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("ClassStats");
                });

            modelBuilder.Entity("Common.Database.Models.Character", b =>
                {
                    b.Navigation("CharacterDeaths");

                    b.Navigation("CharacterInventories");
                });

            modelBuilder.Entity("Common.Database.Models.CharacterStat", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Common.Database.Models.CombatStat", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Common.Database.Models.DungeonStat", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Common.Database.Models.ExplorationStat", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Common.Database.Models.Guild", b =>
                {
                    b.Navigation("GuildMembers");
                });

            modelBuilder.Entity("Common.Database.Models.GuildMember", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Common.Database.Models.KillStat", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Common.Database.Models.Login", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
