Table Accounts {
  id integer [pk, increment]
  name varchar(30) [unique, not null]
  rank smallint [not null, default: 0]
  guild_name varchar(255)
  is_admin boolean [not null]
  is_banned boolean [not null]
  max_chars smallint [not null, default: 0]
  vault_count smallint [not null, default: 0]
  next_char_id smallint [not null, default: 0]
  created_at datetime [not null, default: `NOW()`]

  acc_stats_id integer [ref: - Account_Stats.id, not null, default: 0]
  login_id integer [ref: - Logins.id, not null, default: 0]
  guild_member_id integer [ref: - Guild_Members.id]
  guild_id integer [ref: > Guilds.id]
}

Table Account_Stats {
  id integer [pk, increment]
  best_char_fame "int unsigned" [not null, default: 0]
  current_fame "int unsigned" [not null, default: 0]
  total_fame "int unsigned" [not null, default: 0]
  current_credits "int unsigned" [not null, default: 0]
  total_credits "int unsigned" [not null, default: 0]
}

Table Account_Locks {
  account_id integer [ref: > Accounts.id, not null, default: 0]
  locked_id integer [ref: > Accounts.id, not null, default: 0]
  
  indexes {
    (account_id, locked_id) [pk]
  }
}

Table Account_Ignores {
  account_id integer [ref: > Accounts.id, not null, default: 0]
  ignored_id integer [ref: > Accounts.id, not null, default: 0]
  
  indexes {
    (account_id, ignored_id) [pk]
  }
}

Table Account_Mutes {
  id integer [pk, increment]
  reason varchar(255)
  muted_at datetime [not null, default: `NOW()`]
  expires_at datetime
  
  moderator_id integer [ref: > Accounts.id, not null, default: 0]
  muted_id integer [ref: > Accounts.id, not null, default: 0]
}

Table Account_Bans {
  id integer [pk, increment]
  ban_type integer [not null, default: 0]
  reason varchar(255)
  banned_at datetime [not null, default: `NOW()`]
  expires_at datetime
  
  moderator_id integer [ref: > Accounts.id, not null, default: 0]
  banned_id integer [ref: > Accounts.id, not null, default: 0]
}

Table Account_Skins {
  account_id integer [ref: > Accounts.id]
  skin_type integer [not null, default: 0]
  
  indexes {
    (account_id, skin_type) [pk]
  }
}

Table Account_Vault {
  account_id integer [ref: > Accounts.id]
  slot_id integer [not null]
  item_type "smallint unsigned" [not null, default: 0]
  item_data blob

  indexes {
    (account_id, slot_id) [pk]
  }
}

Table Account_Gifts {
  account_id integer [ref: > Accounts.id]
  slot_id integer [not null]
  item_type "smallint unsigned" [not null, default: 0]
  item_data blob

  indexes {
    (account_id, slot_id) [pk]
  }
}

Table Class_Stats {
  id integer [pk, increment]
  object_type "smallint unsigned" [not null, default: 0]
  best_level "smallint unsigned" [not null, default: 0]
  best_fame "int unsigned" [not null, default: 0]
  
  acc_stats_id integer [ref: > Account_Stats.id, not null, default: 0]
}

Table Logins {
  id integer [pk, increment]
  name varchar(30) [unique, not null]
  password_hash text
  password_salt text
  last_login_at datetime
  ip_address varchar(30)
}

Table Characters {
  id integer [pk, increment]
  acc_char_id integer [not null, default: 0]
  object_type "smallint unsigned" [not null, default: 0]
  level "smallint unsigned" [not null, default: 0]
  current_fame "int unsigned" [not null, default: 0]
  xp_points "int unsigned" [not null, default: 0]
  skin_type "smallint unsigned" [not null, default: 0]
  texture_one "smallint unsigned" [not null, default: 0]
  texture_two "smallint unsigned" [not null, default: 0]
  pet_type "smallint unsigned" [not null, default: 0]
  health_potions "smallint unsigned" [not null, default: 0]
  magic_potions "smallint unsigned" [not null, default: 0]
  is_dead boolean [not null]
  is_deleted boolean [not null]
  has_backpack boolean [not null]
  created_at datetime [not null, default: `NOW()`]
  deleted_at datetime

  acc_id integer [ref: > Accounts.id, not null, default: 0]
  char_stats_id integer [ref: - Character_Stats.id, not null, default: 0]
  explo_stats_id integer [ref: - Exploration_Stats.id, not null, default: 0]
  combat_stats_id integer [ref: - Combat_Stats.id, not null, default: 0]
  kill_stats_id integer [ref: - Kill_Stats.id, not null, default: 0]
  dungeon_stats_id integer [ref: - Dungeon_Stats.id, not null, default: 0]
}

Table Character_Stats {
  id integer [pk, increment]
  hp "int unsigned" [not null, default: 0]
  mp "int unsigned" [not null, default: 0]
  max_hp "int unsigned" [not null, default: 0]
  max_mp "int unsigned" [not null, default: 0]
  attack "int unsigned" [not null, default: 0]
  defense "int unsigned" [not null, default: 0]
  speed "int unsigned" [not null, default: 0]
  dexterity "int unsigned" [not null, default: 0]
  vitality "int unsigned" [not null, default: 0]
  wisdom "int unsigned" [not null, default: 0]
}

Table Character_Inventory {
  character_id integer [ref: > Characters.id]
  slot_id integer [not null]
  item_type "smallint unsigned" [not null, default: 0]
  item_data blob

  indexes {
    (character_id, slot_id) [pk]
  }
}

Table Character_Death {
  id integer [pk, increment]
  dead_at datetime [not null, default: `NOW()`]
  death_fame "int unsigned" [not null, default: 0]

  char_id integer [ref: - Characters.id, not null, default: 0]
}

Table Exploration_Stats {
  id integer [pk, increment]
  tiles_uncovered "int unsigned" [not null, default: 0]
  quests_completed "int unsigned" [not null, default: 0]
  escapes "int unsigned" [not null, default: 0]
  near_death_escapes "int unsigned" [not null, default: 0]
  minutes_active "int unsigned" [not null, default: 0]
  teleports "int unsigned" [not null, default: 0]
}

Table Combat_Stats {
  id integer [pk, increment]
  shots "bigint unsigned" [not null, default: 0]
  shots_hit "int unsigned" [not null, default: 0]
  level_up_assists "int unsigned" [not null, default: 0]
  potions_drank "smallint unsigned" [not null, default: 0]
  abilities_used "smallint unsigned" [not null, default: 0]
  damage_taken "int unsigned" [not null, default: 0]
  damage_dealt "int unsigned" [not null, default: 0]
}

Table Kill_Stats {
  id integer [pk, increment]
  monster_kills "int unsigned" [not null, default: 0]
  monster_assists "int unsigned" [not null, default: 0]
  god_kills "int unsigned" [not null, default: 0]
  god_assists "int unsigned" [not null, default: 0]
  oryx_kills "smallint unsigned" [not null, default: 0]
  oryx_assists "smallint unsigned" [not null, default: 0]
  cube_kills "smallint unsigned" [not null, default: 0]
  cube_assists "smallint unsigned" [not null, default: 0]
  blue_bags "smallint unsigned" [not null, default: 0]
  cyan_bags "smallint unsigned" [not null, default: 0]
  white_bags "smallint unsigned" [not null, default: 0]
}

Table Dungeon_Stats {
  id integer [pk, increment]
  dungeon_name varchar(255)
  completed_count "smallint unsigned" [not null, default: 0]
}

Table Guilds {
  id integer [pk, increment]
  name varchar(255)
  level smallint [not null, default: 0]
  current_fame "int unsigned" [not null, default: 0]
  total_fame "int unsigned" [not null, default: 0]
  guild_board text
  created_at datetime [not null, default: `NOW()`]
}

Table Guild_Members {
  id integer [pk, increment]
  guild_rank smallint [not null, default: 0]
  last_seen_at datetime [not null, default: `NOW()`]
  
  guild_id integer [ref: > Guilds.id, not null, default: 0]
}