Table Accounts {
  id integer [pk, increment]
  name varchar(30) [unique]
  rank smallint
  guild_name varchar(255)
  is_admin boolean
  is_banned boolean
  max_chars smallint
  vault_count smallint
  created_at datetime [default: `NOW()`]

  acc_stats_id integer [ref: - Account_Stats.id]
  login_id integer [ref: - Logins.id]
}

Table Account_Stats {
  id integer [pk, increment]
  best_char_fame "int unsigned"
  current_fame "int unsigned"
  total_fame "int unsigned"
  current_credits "int unsigned"
  total_credits "int unsigned"
}

Table Class_Stats {
  id integer [pk, increment]
  object_type "smallint unsigned"
  best_level "smallint unsigned"
  best_fame "int unsigned"
  
  acc_stats_id integer [ref: > Account_Stats.id]
}

Table Logins {
  id integer [pk, increment]
  name varchar(30) [unique]
  password_hash text
  password_salt text
  last_login_at datetime
  ip_address varchar(30)
}

Table Characters {
  id integer [pk, increment]
  object_type "smallint unsigned"
  level "smallint unsigned"
  current_fame "int unsigned"
  xp_points "int unsigned"
  skin_type "smallint unsigned"
  texture_one "smallint unsigned"
  texture_two "smallint unsigned"
  pet_type "smallint unsigned"
  health_potions "smallint unsigned"
  magic_potions "smallint unsigned"
  is_dead boolean
  is_deleted boolean
  has_backpack boolean
  created_at datetime [default: `NOW()`]
  deleted_at datetime

  acc_id integer [ref: > Accounts.id]
  char_stats_id integer [ref: - Character_Stats.id]
  explo_stats_id integer [ref: - Exploration_Stats.id]
  combat_stats_id integer [ref: - Combat_Stats.id]
  kill_stats_id integer [ref: - Kill_Stats.id]
  dungeon_stats_id integer [ref: - Dungeon_Stats.id]
}

Table Character_Stats {
  id integer [pk, increment]
  hp "int unsigned"
  mp "int unsigned"
  max_hp "int unsigned"
  max_mp "int unsigned"
  attack "int unsigned"
  defense "int unsigned"
  speed "int unsigned"
  dexterity "int unsigned"
  vitality "int unsigned"
  wisdom "int unsigned"
}

Table Character_Inventory {
  character_id integer [ref: > Characters.id]
  slot_id integer
  item_type "smallint unsigned"
  item_data blob

  indexes {
    (character_id, slot_id) [pk]
  }
}

Table Character_Death {
  id integer [pk, increment]
  dead_at datetime [default: `NOW()`]
  death_fame "int unsigned"

  char_id integer [ref: - Characters.id]
}

Table Exploration_Stats {
  id integer [pk, increment]
  tiles_uncovered "int unsigned"
  quests_completed "int unsigned"
  escapes "int unsigned"
  near_death_escapes "int unsigned"
  minutes_active "int unsigned"
  teleports "int unsigned"
}

Table Combat_Stats {
  id integer [pk, increment]
  shots "bigint unsigned"
  shots_hit "int unsigned"
  level_up_assists "int unsigned"
  potions_drank "smallint unsigned"
  abilities_used "smallint unsigned"
  damage_taken "int unsigned"
  damage_dealt "int unsigned"
}

Table Kill_Stats {
  id integer [pk, increment]
  monster_kills "int unsigned"
  monster_assists "int unsigned"
  god_kills "int unsigned"
  god_assists "int unsigned"
  oryx_kills "smallint unsigned"
  oryx_assists "smallint unsigned"
  cube_kills "smallint unsigned"
  cube_assists "smallint unsigned"
  blue_bags "smallint unsigned"
  cyan_bags "smallint unsigned"
  white_bags "smallint unsigned"
}

Table Dungeon_Stats {
  id integer [pk, increment]
  dungeon_name varchar(255)
  completed_count "smallint unsigned"
}

Table Guilds {
  id integer [pk, increment]
  name varchar(255)
  level smallint
  current_fame "int unsigned"
  total_fame "int unsigned"
  guild_board text
  created_at datetime [default: `NOW()`]
}

Table Guild_Members {
  guild_id integer [ref: > Guilds.id]
  account_id integer [ref: - Accounts.id]
  guild_rank smallint
  last_seen_at datetime [default: `NOW()`]

  indexes {
    (guild_id, account_id) [pk]
  }
}