using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EventRouterGenerator;

[Generator]
public class EventRouterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax c && c.Identifier.Text == "EventRouter",
                transform: static (ctx, _) => GetClassSymbol(ctx))
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(classDeclarations, static (spc, symbol) => Execute(spc, symbol!));
    }

    private static INamedTypeSymbol? GetClassSymbol(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        return context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol routerSymbol)
    {
        // Extract all public/internal fields of type EventBus<T>
        var eventFields = routerSymbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => f.Type is INamedTypeSymbol { Name: "EventBus", IsGenericType: true })
            .Select(f => (FieldName: f.Name, EventType: ((INamedTypeSymbol)f.Type).TypeArguments[0]))
            .ToList();

        if (eventFields.Count == 0) return;

        var routerNamespace = routerSymbol.ContainingNamespace.ToDisplayString();
        var routerClassName = routerSymbol.Name;

        // -------------------------------------------------------------
        // 1. Generate EventRouter.g.cs (Add, Remove, Invoke)
        // -------------------------------------------------------------
        var routerSb = new StringBuilder();
        routerSb.AppendLine("// <auto-generated />");
        routerSb.AppendLine("#nullable enable");
        routerSb.AppendLine($"namespace {routerNamespace};");
        routerSb.AppendLine();
        routerSb.AppendLine($"public partial class {routerClassName}");
        routerSb.AppendLine("{");

        foreach (var (fieldName, eventType) in eventFields)
        {
            var eventTypeName = eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            routerSb.AppendLine($"    public void Add(EventHandler<{eventTypeName}> handler) => {fieldName}.Add(handler);");
            routerSb.AppendLine($"    public void Remove(EventHandler<{eventTypeName}> handler) => {fieldName}.Remove(handler);");
            routerSb.AppendLine($"    public void Invoke(ref {eventTypeName} evt) => {fieldName}.Invoke(ref evt);");
            routerSb.AppendLine();
        }

        routerSb.AppendLine("}");
        context.AddSource($"{routerClassName}.g.cs", SourceText.From(routerSb.ToString(), Encoding.UTF8));

        // -------------------------------------------------------------
        // 2. Generate EventSystem.g.cs (Subscribe, Unsubscribe, Invoke)
        // -------------------------------------------------------------
        var systemSb = new StringBuilder();
        systemSb.AppendLine("// <auto-generated />");
        systemSb.AppendLine("#nullable enable");
        systemSb.AppendLine("using Arch.Core;");
        systemSb.AppendLine("using GameServer.Game.Entities.Events;");
        systemSb.AppendLine();
        systemSb.AppendLine("namespace GameServer.Game.Entities.Systems;");
        systemSb.AppendLine();
        systemSb.AppendLine("public partial class EventSystem");
        systemSb.AppendLine("{");

        foreach (var (_, eventType) in eventFields)
        {
            var eventTypeName = eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            // Subscribe overload
            systemSb.AppendLine($"    public void Subscribe(Entity entity, {routerNamespace}.EventHandler<{eventTypeName}> evtHandler)");
            systemSb.AppendLine("    {");
            systemSb.AppendLine("        if (!_eventRouters.TryGetValue(entity, out var eventRouter))");
            systemSb.AppendLine("            eventRouter = _eventRouters[entity] = new EventRouter(entity);");
            systemSb.AppendLine("        eventRouter.Add(evtHandler);");
            systemSb.AppendLine("    }");
            systemSb.AppendLine();

            // Unsubscribe overload
            systemSb.AppendLine($"    public void Unsubscribe(Entity entity, {routerNamespace}.EventHandler<{eventTypeName}> evtHandler)");
            systemSb.AppendLine("    {");
            systemSb.AppendLine("        if (!_eventRouters.TryGetValue(entity, out var eventRouter))");
            systemSb.AppendLine("            return;");
            systemSb.AppendLine("        eventRouter.Remove(evtHandler);");
            systemSb.AppendLine("    }");
            systemSb.AppendLine();

            // Invoke overload
            systemSb.AppendLine($"    public void Invoke(Entity entity, ref {eventTypeName} evt)");
            systemSb.AppendLine("    {");
            systemSb.AppendLine("        if (!_eventRouters.TryGetValue(entity, out var eventRouter))");
            systemSb.AppendLine("            eventRouter = _eventRouters[entity] = new EventRouter(entity);");
            systemSb.AppendLine("        eventRouter.Invoke(ref evt);");
            systemSb.AppendLine("    }");
            systemSb.AppendLine();
        }

        systemSb.AppendLine("}");
        context.AddSource("EventSystem.g.cs", SourceText.From(systemSb.ToString(), Encoding.UTF8));
    }
}