<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common\Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="LiteDB" Version="5.0.21" />

      <PackageReference Include="Grpc.AspNetCore" Version="2.66.0" />
      <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.66.0" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="..\Common\Database\Protos\db_service.proto" GrpcServices="Server" />
    </ItemGroup>

</Project>

