Table Accounts {
  id integer [pk, increment]
  name varchar(30) [unique]
  rank smallint
  is_admin boolean
  is_banned boolean
  created_ad datetime [default: `NOW()`]
}

Table Account_Stats {
  id integer [pk, increment]
  best_char_fame "unsigned int"
  current_fame "unsigned int"
  total_fame "unsigned int"
  current_credits "unsigned int"
  total_credits "unsigned int"
}

Table Class_Stats {
  id integer [pk, increment]
  object_type "unsigned smallint"
  best_level "unsigned smallint"
  best_fame "unsigned int"
}

Table Logins {
  id integer [pk, increment]
  name varchar(30) [unique]
  password_hash text
  password_salt text
  last_login_at datetime
}

Table Characters {
  id integer [pk, increment]
  object_type "unsigned smallint"
  level "unsigned smallint"
  current_fame "unsigned int"
  xp_points "unsigned int"
  skin_type "unsigned smallint"
  texture_one "unsigned smallint"
  texture_two "unsigned smallint"
  pet_type "unsigned smallint"
  health_potions "unsigned smallint"
  magic_potions "unsigned smallint"
  is_dead boolean
  is_deleted boolean
  has_backpack boolean
  created_at datetime [default: `NOW()`]
  deleted_at datetime
}

Table Character_Stats {
  id integer [pk, increment]
  hp "unsigned int"
  mp "unsigned int"
  max_hp "unsigned int"
  max_mp "unsigned int"
  attack "unsigned int"
  defense "unsigned int"
  speed "unsigned int"
  dexterity "unsigned int"
  vitality "unsigned int"
  wisdom "unsigned int"
}

Table Character_Inventory {
  character_id integer
  slot_id integer
  item_type "unsigned smallint"
  item_data blob

  indexes {
    (character_id, slot_id) [pk]
  }
}

Table Character_Death {
  id integer [pk, increment]
  dead_at datetime [default: `NOW()`]
  death_fame "unsigned int"
}

Table Exploration_Stats {
  id integer [pk, increment]
  tiles_uncovered "unsigned int"
  quests_completed "usigned int"
  escapes "unsigned int"
  near_death_escapes "unsigned int"
  minutes_active "unsigned int"
  teleports "unsigned int"
}

Table Combat_Stats {
  id integer [pk, increment]
  shots "unsigned bigint"
  shots_hit "usigned int"
  level_up_assists "unsigned int"
  potions_drank "unsigned smallint"
  abilities_used "unsigned smallint"
  damage_taken "unsigned int"
  damage_dealt "unsigned int"
}

Table Kill_Stats {
  id integer [pk, increment]
  monster_kills "unsigned int"
  monster_assists "usigned int"
  god_kills "unsigned int"
  god_assists "unsigned int"
  oryx_kills "unsigned smallint"
  oryx_assists "unsigned smallint"
  cube_kills "unsigned smallint"
  cube_assists "unsigned smallint"
  blue_bags "unsigned smallint"
  cyan_bags "unsigned smallint"
  white_bags "unsigned smallint"
}

Table Dungeon_Stats {
  id integer [pk, increment]
  dungeon_name varchar(255)
  completed_count "unsigned smallint"
}

Table Guilds {
  id integer [pk, increment]
  name varchar(255)
  level smallint
  current_fame "unsigned integer"
  total_fame "unsigned integer"
  guild_board text
  created_at datetime [default: `NOW()`]
}

Table Guild_Members {
  guild_id integer
  account_id integer
  guild_rank smallint
  last_seen_at datetime [default: `NOW()`]
}